### ISSUE TITLE
运行go-cqhttp-master之后使用cmd的命令npm start运行cq-picsearcher-bot。发图片之后没反应

### ISSUE THREAD

**Issue by vanish666** [Tsuk1ko/cq-picsearcher-bot#115]
1. Bug 描述
   运行两个软件后给机器人发图片没反应
2. 截图、日志、配置（issue 内上传图片或文件可直接粘贴）
   
![屏幕截图 2020-12-13 163001](https://user-images.githubusercontent.com/47470803/102007698-39c36f80-3d66-11eb-8a09-79eef476a566.png)

bug描述：
D:\ai-bot\go-cqhttp-master\cq-picsearcher-bot\node_modules\sqlite3\lib\sqlite3-binding.js:1

Error: Cannot find module 'D:\ai-bot\go-cqhttp-master\cq-picsearcher-bot\node_modules\sqlite3\lib\binding\node-v83-win32-x64\node_sqlite3.node'

Require stack:

- D:\ai-bot\go-cqhttp-master\cq-picsearcher-bot\node_modules\sqlite3\lib\sqlite3-binding.js
- D:\ai-bot\go-cqhttp-master\cq-picsearcher-bot\node_modules\sqlite3\lib\sqlite3.js
- D:\ai-bot\go-cqhttp-master\cq-picsearcher-bot\src\cache.js
- D:\ai-bot\go-cqhttp-master\cq-picsearcher-bot\main.js
- D:\ai-bot\go-cqhttp-master\cq-picsearcher-bot\index.js
  at new MODULE_NOT_FOUND (C:\Users\Dgzt\cq-picsearcher-bot\node_modules\esm\esm.js:1)
  at Proxy.<anonymous> (C:\Users\Dgzt\cq-picsearcher-bot\node_modules\esm\esm.js:1)
  at Proxy.<anonymous> (C:\Users\Dgzt\cq-picsearcher-bot\node_modules\esm\esm.js:1)
  at Object.<anonymous> (C:\Users\Dgzt\cq-picsearcher-bot\node_modules\esm\esm.js:1)
  at Object.t (C:\Users\Dgzt\cq-picsearcher-bot\node_modules\esm\esm.js:1)
  at n (C:\Users\Dgzt\cq-picsearcher-bot\node_modules\esm\esm.js:1)
  at Object.<anonymous> (C:\Users\Dgzt\cq-picsearcher-bot\node_modules\sqlite3\lib\sqlite3-binding.js:4:15)
  at Object.<anonymous> (C:\Users\Dgzt\cq-picsearcher-bot\node_modules\esm\esm.js:1)
  at Object.<anonymous> (C:\Users\Dgzt\cq-picsearcher-bot\node_modules\esm\esm.js:1)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

3. 运行环境
   - 系统win10 64位
   - Node v14.15.1
   - go-cqhttp-master
   - cq-picsearcher-bot 2.20.5

**Comment by Tsuk1ko** [comment]
https://github.com/Tsuk1ko/cq-picsearcher-bot/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#tips
