### ISSUE TITLE
机器人在npm start后没有反应

### ISSUE THREAD

**Issue by MoAccelerator** [Tsuk1ko/cq-picsearcher-bot#122]
大佬您好，我遇到了每次npm或者yarn都会卡在最后一步的问题（npm是卡在node-pre-gyp，yarn是卡在sqlite3。由于我不是很懂yarn 所以我就没研究直接放弃yarn了）
![image](https://user-images.githubusercontent.com/45995147/102913013-1bbde380-44b9-11eb-9390-92d0a912636c.png)
然后我手动指定源进行安装“npm install canvas --canvas_binary_host_mirror=https://npm.taobao.org/mirrors/node-canvas-prebuilt/”
安装之后可以直接npm i，之后我npm start，然后程序就启动了，但是并没有任何反应，cqhttp那边在正常运行，我起初以为是我版本的问题，从最新的go-cqhttp-v0.9.35-fix1降级到go-cqhttp-v0.9.32（ps:我前几天刚在windows服务器上面部署过 我已经完全按照当时的环境部署 但是却一直无法正常运行）
![image](https://user-images.githubusercontent.com/45995147/102914020-a18e5e80-44ba-11eb-91c1-ceb52c39e4c2.png)
![image](https://user-images.githubusercontent.com/45995147/102914119-cc78b280-44ba-11eb-9d64-bf82eeb7d9fb.png)

我尝试了ubuntu18.04和windows server 2019两个系统，而且试用了两款不同运营商的服务器，进行过各种版本的尝试，但都无法正常运作。
我个人猜测可能是设置的源出现了问题 导致无法构建node-pre-gyp，但是我测试了默认源和淘宝源都不能完成构建，所以想请大佬帮我解决一下这个问题，谢谢！

**Comment by Tsuk1ko** [comment]
你先停止 pm2 守护，先 `npm run test` 看看，从截图来看你没有成功启动

**Comment by Tsuk1ko** [comment]
如果还是 module not found 的话，尝试删除 node_modules 文件夹再重新安装

**Comment by MoAccelerator** [comment]
npm run test之后提示缺少sqlite3 然后我使用"npm install sqlite3"之后会提示这样的报错


> cq-picsearcher-bot@2.21.5 test /root/cq-picsearcher-bot
> node index.js

12/23/2020, 5:10:14 AM 配置已加载
12/23/2020, 5:10:17 AM 连接中[/event]#1
12/23/2020, 5:10:17 AM 连接中[/api]#1
12/23/2020, 5:10:17 AM 连接错误[/event]
SocketError: Failed to establish the websocket connection.
    at W3CWebSocket._sock.addEventListener.once (/root/cq-picsearcher-bot/node_modules/cq-websocket/src/index.js:494:70)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/root/cq-picsearcher-bot/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (/root/cq-picsearcher-bot/node_modules/websocket/lib/W3CWebSocket.js:217:14)
    at WebSocketClient.<anonymous> (/root/cq-picsearcher-bot/node_modules/websocket/lib/W3CWebSocket.js:59:25)
    at WebSocketClient.emit (events.js:315:20)
    at WebSocketClient.EventEmitter.emit (domain.js:467:12)
    at ClientRequest.handleRequestError (/root/cq-picsearcher-bot/node_modules/websocket/lib/WebSocketClient.js:227:14)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at Socket.socketErrorListener (_http_client.js:469:9)
12/23/2020, 5:10:17 AM 连接失败[/event]#1
12/23/2020, 5:10:17 AM 连接错误[/api]
SocketError: Failed to establish the websocket connection.
    at W3CWebSocket._sock.addEventListener.once (/root/cq-picsearcher-bot/node_modules/cq-websocket/src/index.js:494:70)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/root/cq-picsearcher-bot/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (/root/cq-picsearcher-bot/node_modules/websocket/lib/W3CWebSocket.js:217:14)
    at WebSocketClient.<anonymous> (/root/cq-picsearcher-bot/node_modules/websocket/lib/W3CWebSocket.js:59:25)
    at WebSocketClient.emit (events.js:315:20)
    at WebSocketClient.EventEmitter.emit (domain.js:467:12)
    at ClientRequest.handleRequestError (/root/cq-picsearcher-bot/node_modules/websocket/lib/WebSocketClient.js:227:14)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at Socket.socketErrorListener (_http_client.js:469:9)
12/23/2020, 5:10:17 AM 连接失败[/api]#1
12/23/2020, 5:10:22 AM 连接中[/event]#2
12/23/2020, 5:10:22 AM 连接错误[/event]
SocketError: Failed to establish the websocket connection.
    at W3CWebSocket._sock.addEventListener.once (/root/cq-picsearcher-bot/node_modules/cq-websocket/src/index.js:494:70)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/root/cq-picsearcher-bot/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (/root/cq-picsearcher-bot/node_modules/websocket/lib/W3CWebSocket.js:217:14)
    at WebSocketClient.<anonymous> (/root/cq-picsearcher-bot/node_modules/websocket/lib/W3CWebSocket.js:59:25)
    at WebSocketClient.emit (events.js:315:20)
    at WebSocketClient.EventEmitter.emit (domain.js:467:12)
    at ClientRequest.handleRequestError (/root/cq-picsearcher-bot/node_modules/websocket/lib/WebSocketClient.js:227:14)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at Socket.socketErrorListener (_http_client.js:469:9)
12/23/2020, 5:10:22 AM 连接失败[/event]#2
12/23/2020, 5:10:22 AM 连接中[/api]#2
12/23/2020, 5:10:22 AM 连接错误[/api]
SocketError: Failed to establish the websocket connection.
    at W3CWebSocket._sock.addEventListener.once (/root/cq-picsearcher-bot/node_modules/cq-websocket/src/index.js:494:70)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/root/cq-picsearcher-bot/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (/root/cq-picsearcher-bot/node_modules/websocket/lib/W3CWebSocket.js:217:14)
    at WebSocketClient.<anonymous> (/root/cq-picsearcher-bot/node_modules/websocket/lib/W3CWebSocket.js:59:25)
    at WebSocketClient.emit (events.js:315:20)
    at WebSocketClient.EventEmitter.emit (domain.js:467:12)
    at ClientRequest.handleRequestError (/root/cq-picsearcher-bot/node_modules/websocket/lib/WebSocketClient.js:227:14)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at Socket.socketErrorListener (_http_client.js:469:9)
12/23/2020, 5:10:22 AM 连接失败[/api]#2
12/23/2020, 5:10:27 AM 连接中[/event]#3
12/23/2020, 5:10:27 AM 连接错误[/event]
SocketError: Failed to establish the websocket connection.
    at W3CWebSocket._sock.addEventListener.once (/root/cq-picsearcher-bot/node_modules/cq-websocket/src/index.js:494:70)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/root/cq-picsearcher-bot/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (/root/cq-picsearcher-bot/node_modules/websocket/lib/W3CWebSocket.js:217:14)
    at WebSocketClient.<anonymous> (/root/cq-picsearcher-bot/node_modules/websocket/lib/W3CWebSocket.js:59:25)
    at WebSocketClient.emit (events.js:315:20)
    at WebSocketClient.EventEmitter.emit (domain.js:467:12)
    at ClientRequest.handleRequestError (/root/cq-picsearcher-bot/node_modules/websocket/lib/WebSocketClient.js:227:14)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at Socket.socketErrorListener (_http_client.js:469:9)
12/23/2020, 5:10:27 AM 连接失败[/event]#3
12/23/2020, 5:10:27 AM 连接中[/api]#3
12/23/2020, 5:10:27 AM 连接错误[/api]
SocketError: Failed to establish the websocket connection.
    at W3CWebSocket._sock.addEventListener.once (/root/cq-picsearcher-bot/node_modules/cq-websocket/src/index.js:494:70)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/root/cq-picsearcher-bot/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (/root/cq-picsearcher-bot/node_modules/websocket/lib/W3CWebSocket.js:217:14)
    at WebSocketClient.<anonymous> (/root/cq-picsearcher-bot/node_modules/websocket/lib/W3CWebSocket.js:59:25)
    at WebSocketClient.emit (events.js:315:20)
    at WebSocketClient.EventEmitter.emit (domain.js:467:12)
    at ClientRequest.handleRequestError (/root/cq-picsearcher-bot/node_modules/websocket/lib/WebSocketClient.js:227:14)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at Socket.socketErrorListener (_http_client.js:469:9)
12/23/2020, 5:10:27 AM 连接失败[/api]#3


12/23/2020, 5:10:32 AM 连接中[/event]#4
12/23/2020, 5:10:32 AM 连接错误[/event]
SocketError: Failed to establish the websocket connection.
    at W3CWebSocket._sock.addEventListener.once (/root/cq-picsearcher-bot/node_modules/cq-websocket/src/index.js:494:70)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/root/cq-picsearcher-bot/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (/root/cq-picsearcher-bot/node_modules/websocket/lib/W3CWebSocket.js:217:14)
    at WebSocketClient.<anonymous> (/root/cq-picsearcher-bot/node_modules/websocket/lib/W3CWebSocket.js:59:25)
    at WebSocketClient.emit (events.js:315:20)
    at WebSocketClient.EventEmitter.emit (domain.js:467:12)
    at ClientRequest.handleRequestError (/root/cq-picsearcher-bot/node_modules/websocket/lib/WebSocketClient.js:227:14)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at Socket.socketErrorListener (_http_client.js:469:9)
12/23/2020, 5:10:32 AM 连接失败[/event]#4
12/23/2020, 5:10:32 AM 连接中[/api]#4
12/23/2020, 5:10:32 AM 连接错误[/api]
SocketError: Failed to establish the websocket connection.
    at W3CWebSocket._sock.addEventListener.once (/root/cq-picsearcher-bot/node_modules/cq-websocket/src/index.js:494:70)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/root/cq-picsearcher-bot/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (/root/cq-picsearcher-bot/node_modules/websocket/lib/W3CWebSocket.js:217:14)
    at WebSocketClient.<anonymous> (/root/cq-picsearcher-bot/node_modules/websocket/lib/W3CWebSocket.js:59:25)
    at WebSocketClient.emit (events.js:315:20)
    at WebSocketClient.EventEmitter.emit (domain.js:467:12)
    at ClientRequest.handleRequestError (/root/cq-picsearcher-bot/node_modules/websocket/lib/WebSocketClient.js:227:14)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at Socket.socketErrorListener (_http_client.js:469:9)
12/23/2020, 5:10:32 AM 连接失败[/api]#4




在您的建议下 我用git pull更新之后，删除了node_modules文件夹 并且用yarn安装
![image](https://user-images.githubusercontent.com/45995147/102933962-348cc000-44de-11eb-9da7-cdd6b1aecef8.png)
![image](https://user-images.githubusercontent.com/45995147/102934052-63a33180-44de-11eb-8491-265d7bc622b8.png)

看样子是成功了，但是我启动之后仍然没有反应....
![image](https://user-images.githubusercontent.com/45995147/102934117-86354a80-44de-11eb-9635-a52d71156c1c.png)

**Comment by MoAccelerator** [comment]
还有个很奇怪的问题 就是我进行npm run test之后是正常运作的
![image](https://user-images.githubusercontent.com/45995147/102934930-158f2d80-44e0-11eb-981c-bea67460e67d.png)
当我使用npm start之后就又没反应了
![image](https://user-images.githubusercontent.com/45995147/102934978-29d32a80-44e0-11eb-8a44-ae0b2a936142.png)
![image](https://user-images.githubusercontent.com/45995147/102935019-3e172780-44e0-11eb-8157-ceefc9ac68da.png)

**Comment by Tsuk1ko** [comment]
```bash
npx pm2 kill
npm start
```

**Comment by MoAccelerator** [comment]
终于成功了，谢谢大佬！！
