### ISSUE TITLE
context.message有关的类型错误

### ISSUE THREAD

**Issue by ZhaoWeicheng98** [Tsuk1ko/cq-picsearcher-bot#126]
# Bug描述

Bot可以正常启动，并向主人QQ发送“已上线#1”信息，但无法处理任何消息。一旦接受到任何消息（包括私聊和群内发言，就会报告有关context.message的错误，例如：
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: context.message.charAt is not a function
    at commonHandle (F:\cq-picsearcher-bot\main.js:151:37)
    at groupMsg (F:\cq-picsearcher-bot\main.js:325:7)
    at CQEventBus._emitThroughHierarchy (F:\cq-picsearcher-bot\node_modules\cq-websocket\src\event-bus.js:157:46)
    at CQEventBus.emit (F:\cq-picsearcher-bot\node_modules\cq-websocket\src\event-bus.js:131:17)
    at Function._handle (F:\cq-picsearcher-bot\node_modules\cq-websocket\src\index.js:237:32)
    at W3CWebSocket._onMessage (F:\cq-picsearcher-bot\node_modules\cq-websocket\src\index.js:451:18)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (F:\cq-picsearcher-bot\node_modules\yaeti\lib\EventTarget.js:115:12)
    at W3CWebSocket.onMessage (F:\cq-picsearcher-bot\node_modules\websocket\lib\W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (F:\cq-picsearcher-bot\node_modules\websocket\lib\W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:315:20)
```

通过添加console.log打印context.message后发现其结构为
```
[
 {
  "data":"xxx",
  "type":"xxx"
 }
]
```
而非相关代码中认为的string类型，这可能是错误原因。

# 运行环境

+ 系统： Windows 10 amd64
+ node.js版本：14.15.3
+ go-cqhttp版本：0.9.37-fix1
+ cq-picsearcher-bot 版本：2.21.6

**Comment by Tsuk1ko** [comment]
本项目目前只支持 `post_message_format` 为 `string`

https://github.com/Mrs4s/go-cqhttp/blob/master/docs/config.md

**Comment by ZhaoWeicheng98** [comment]
> 本项目目前只支持 `post_message_format` 为 `string`
> 
> https://github.com/Mrs4s/go-cqhttp/blob/master/docs/config.md

感谢，问题已解决（恕我可能星际玩家，wiki中没有看见这一条，如果确实没有的话烦请增加，感谢）

**Comment by Tsuk1ko** [comment]
确实没有，我会加上的
