### ISSUE TITLE
npm start无法启动，但npm run test运行正常

### ISSUE THREAD

**Issue by SakuraChanNya** [Tsuk1ko/cq-picsearcher-bot#222]
1. Bug 描述
   - npm start无法启动，但npm run test运行正常
   - cq-picsearcher-bot 2.29.10无问题，升级到2.29.11后就无法通过npm start启动了，但npm run test所有功能运行正常
2. 截图、日志、配置（issue 内上传图片或文件可直接粘贴）
```
root@VM-4-5-debian:~/cq-picsearcher-bot-2.29.11# npm start

> cq-picsearcher-bot@2.29.11 start /root/cq-picsearcher-bot-2.29.11
> pm2 start ecosystem.config.js

[PM2] Applying action restartProcessId on app [cqps](ids: [ 0 ])
[PM2][ERROR] Process 0 not found
Process 0 not found
/root/cq-picsearcher-bot-2.29.11/node_modules/pm2/lib/API.js:1720
        acted.push(proc.pm2_env ? proc.pm2_env.pm_id : proc.pm_id)
                        ^

TypeError: Cannot read property 'pm2_env' of undefined
    at /root/cq-picsearcher-bot-2.29.11/node_modules/pm2/lib/API.js:1720:25
    at Array.forEach (<anonymous>)
    at API.speedList (/root/cq-picsearcher-bot-2.29.11/node_modules/pm2/lib/API.js:1719:18)
    at /root/cq-picsearcher-bot-2.29.11/node_modules/pm2/lib/binaries/CLI.js:301:15
    at wrapper (/root/cq-picsearcher-bot-2.29.11/node_modules/async/internal/once.js:12:16)
    at replenish (/root/cq-picsearcher-bot-2.29.11/node_modules/async/internal/eachOfLimit.js:76:25)
    at iterateeCallback (/root/cq-picsearcher-bot-2.29.11/node_modules/async/internal/eachOfLimit.js:65:17)
    at /root/cq-picsearcher-bot-2.29.11/node_modules/async/internal/onlyOnce.js:12:16
    at /root/cq-picsearcher-bot-2.29.11/node_modules/pm2/lib/binaries/CLI.js:292:11
    at /root/cq-picsearcher-bot-2.29.11/node_modules/pm2/lib/API.js:334:21
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cq-picsearcher-bot@2.29.11 start: `pm2 start ecosystem.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cq-picsearcher-bot@2.29.11 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-01T10_31_27_923Z-debug.log
root@VM-4-5-debian:~/cq-picsearcher-bot-2.29.11# sudo npm start

> cq-picsearcher-bot@2.29.11 start /root/cq-picsearcher-bot-2.29.11
> pm2 start ecosystem.config.js

[PM2] Applying action restartProcessId on app [cqps](ids: [ 0 ])
[PM2][ERROR] Process 0 not found
Process 0 not found
/root/cq-picsearcher-bot-2.29.11/node_modules/pm2/lib/API.js:1720
        acted.push(proc.pm2_env ? proc.pm2_env.pm_id : proc.pm_id)
                        ^

TypeError: Cannot read property 'pm2_env' of undefined
    at /root/cq-picsearcher-bot-2.29.11/node_modules/pm2/lib/API.js:1720:25
    at Array.forEach (<anonymous>)
    at API.speedList (/root/cq-picsearcher-bot-2.29.11/node_modules/pm2/lib/API.js:1719:18)
    at /root/cq-picsearcher-bot-2.29.11/node_modules/pm2/lib/binaries/CLI.js:301:15
    at wrapper (/root/cq-picsearcher-bot-2.29.11/node_modules/async/internal/once.js:12:16)
    at replenish (/root/cq-picsearcher-bot-2.29.11/node_modules/async/internal/eachOfLimit.js:76:25)
    at iterateeCallback (/root/cq-picsearcher-bot-2.29.11/node_modules/async/internal/eachOfLimit.js:65:17)
    at /root/cq-picsearcher-bot-2.29.11/node_modules/async/internal/onlyOnce.js:12:16
    at /root/cq-picsearcher-bot-2.29.11/node_modules/pm2/lib/binaries/CLI.js:292:11
    at /root/cq-picsearcher-bot-2.29.11/node_modules/pm2/lib/API.js:334:21
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cq-picsearcher-bot@2.29.11 start: `pm2 start ecosystem.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cq-picsearcher-bot@2.29.11 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-01T10_32_03_486Z-debug.log
```
3. 运行环境
   - 系统是linux，系统版本是Debian10.2
   - node.js v14.17.1
   - go-cqhttp v1.0.0-beta4
   - cq-picsearcher-bot 2.29.11

**Comment by Tsuk1ko** [comment]
试试
```
npx pm2 kill
npm start
```

**Comment by SakuraChanNya** [comment]
> 试试
> 
> ```
> npx pm2 kill
> npm start
> ```

可以了，谢谢大佬~

**Comment by ChrisKimZHT** [comment]
挺好，我更新后也出这问题了，原来这么简单就解决了
