### ISSUE TITLE
能否添加一个语言库检测到说的话然后执行函数

### ISSUE THREAD

**Issue by huankong233** [Tsuk1ko/cq-picsearcher-bot#279]
能否添加一个语言库检测到说的话然后执行函数

比如说，我说咕咕可以去执行gugu函数

**Comment by huankong233** [comment]
嗯。。我想我可以通过修改源码来实现

**Comment by Tsuk1ko** [comment]
目前不考虑，语言库只用来处理处理最简单的固定回答

计划 v3 重构的时候会加入插件功能可以自行编写插件

**Comment by huankong233** [comment]
好的，期待一下。

**Comment by huankong233** [comment]
对了搜图时http://www.ascii2d.net/
经常返回503有办法处理吗

**Comment by Tsuk1ko** [comment]
> 对了搜图时[http://www.ascii2d.net](http://www.ascii2d.net/) 经常返回503有办法处理吗

不清楚，没怎么遇到过 503

**Comment by huankong233** [comment]
> > 对了搜图时[http://www.ascii2d.net](http://www.ascii2d.net/) 经常返回503有办法处理吗
> 
> 不清楚，没怎么遇到过 503

嗯，问你个问题哈，怎么调用API，我想判断一下群里的人是不是管理员，不然写死了麻烦。

**Comment by Tsuk1ko** [comment]
仿照其他文件用 `global.bot()`

**Comment by huankong233** [comment]
> 仿照其他文件用 `global.bot()`，可用 API 看文档
> 
> https://docs.go-cqhttp.org/api/

比如我要调用
https://docs.go-cqhttp.org/api/#%E8%8E%B7%E5%8F%96%E7%BE%A4%E6%88%90%E5%91%98%E4%BF%A1%E6%81%AF
这个API，函数内我应该怎么传入参数。
![image](https://user-images.githubusercontent.com/49610758/147591056-857b45c4-ac2f-43ce-9fde-3110bfa06e20.png)

**Comment by Tsuk1ko** [comment]
```js
global.bot('get_group_member_info', { group_id, user_id })
```

还有这返回的是 Promise……

**Comment by huankong233** [comment]
> ```js
> global.bot('get_group_member_info', { group_id, user_id })
> ```
> 
> 还有这返回的是 Promise……
谢谢。
Wiki里也可以写一下，不然都不知道怎么写哈哈哈。

**Comment by huankong233** [comment]
今天突然出现的bug

不知道是不是更新了之后出现的

要给拿个文件提权啊


`Error: EACCES: permission denied, mkdir '/root/.pm2/logs'
    at Object.mkdirSync (node:fs:1336:3)
    at mkdirpNativeSync (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
    at Function.mkdirpSync [as sync] (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/node_modules/mkdirp/index.js:21:7)
    at module.exports.Client.initFileStructure (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:133:25)
    at new module.exports (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:38:8)
    at new API (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
Error: EACCES: permission denied, mkdir '/root/.pm2/pids'
    at Object.mkdirSync (node:fs:1336:3)
    at mkdirpNativeSync (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
    at Function.mkdirpSync [as sync] (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/node_modules/mkdirp/index.js:21:7)
    at module.exports.Client.initFileStructure (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:141:25)
    at new module.exports (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:38:8)
    at new API (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
Error: EACCES: permission denied, open '/root/.pm2/module_conf.json'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2155:35)
    at module.exports.Client.initFileStructure (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:149:10)
    at new module.exports (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:38:8)
    at new API (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
Error: EACCES: permission denied, mkdir '/root/.pm2/modules'
    at Object.mkdirSync (node:fs:1336:3)
    at mkdirpNativeSync (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
    at Function.mkdirpSync [as sync] (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/node_modules/mkdirp/index.js:21:7)
    at module.exports.Client.initFileStructure (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:157:25)
    at new module.exports (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:38:8)
    at new API (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)

                        -------------

__/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
 _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
  _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
   _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
    _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
     _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
      _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
       _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
        _\///______________\///______________\///__\///////////////__


                          Runtime Edition

        PM2 is a Production Process Manager for Node.js applications
                     with a built-in Load Balancer.

                Start and Daemonize any application:
                $ pm2 start app.js

                Load Balance 4 instances of api.js:
                $ pm2 start api.js -i 4

                Monitor in production:
                $ pm2 monitor

                Make pm2 auto-boot at server restart:
                $ pm2 startup

                To go further checkout:
                http://pm2.io/


                        -------------

Error: EACCES: permission denied, open '/root/.pm2/module_conf.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.Configuration.getAllSync (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Configuration.js:299:26)
    at Object.Configuration.getSync (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Configuration.js:270:30)
    at new API (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/API.js:117:44)
    at Object.<anonymous> (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/@pm2/agent/src/InteractorClient.js:58
          if (stats.uid === 0) {
                    ^

TypeError: Cannot read properties of undefined (reading 'uid')
    at /www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/@pm2/agent/src/InteractorClient.js:58:21
    at FSReqCallback.oncomplete (node:fs:198:21)

Node.js v17.3.0`

**Comment by huankong233** [comment]
应该是我服务器的问题

**Comment by Tsuk1ko** [comment]
```
npm run kill
npm start
```

**Comment by huankong233** [comment]
Last login: Sun Jan  2 01:16:25 2022 from 127.0.0.1
[root@10-7-47-30 ~]# cd /www/wwwroot/qq机器人/cq-picsearcher-bot-master
[root@10-7-47-30 cq-picsearcher-bot-master]# npm run kill

> cq-picsearcher-bot@2.31.1 kill
> pm2 kill

Error: EACCES: permission denied, mkdir '/root/.pm2/logs'
    at Object.mkdirSync (node:fs:1336:3)
    at mkdirpNativeSync (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
    at Function.mkdirpSync [as sync] (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/node_modules/mkdirp/index.js:21:7)
    at module.exports.Client.initFileStructure (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:133:25)
    at new module.exports (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:38:8)
    at new API (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
Error: EACCES: permission denied, mkdir '/root/.pm2/pids'
    at Object.mkdirSync (node:fs:1336:3)
    at mkdirpNativeSync (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
    at Function.mkdirpSync [as sync] (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/node_modules/mkdirp/index.js:21:7)
    at module.exports.Client.initFileStructure (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:141:25)
    at new module.exports (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:38:8)
    at new API (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
Error: EACCES: permission denied, open '/root/.pm2/module_conf.json'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2155:35)
    at module.exports.Client.initFileStructure (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:149:10)
    at new module.exports (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:38:8)
    at new API (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
Error: EACCES: permission denied, mkdir '/root/.pm2/modules'
    at Object.mkdirSync (node:fs:1336:3)
    at mkdirpNativeSync (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
    at Function.mkdirpSync [as sync] (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/node_modules/mkdirp/index.js:21:7)
    at module.exports.Client.initFileStructure (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:157:25)
    at new module.exports (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:38:8)
    at new API (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)

                        -------------

__/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
 _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
  _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
   _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
    _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
     _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
      _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
       _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
        _\///______________\///______________\///__\///////////////__


                          Runtime Edition

        PM2 is a Production Process Manager for Node.js applications
                     with a built-in Load Balancer.

                Start and Daemonize any application:
                $ pm2 start app.js

                Load Balance 4 instances of api.js:
                $ pm2 start api.js -i 4

                Monitor in production:
                $ pm2 monitor

                Make pm2 auto-boot at server restart:
                $ pm2 startup

                To go further checkout:
                http://pm2.io/


                        -------------

Error: EACCES: permission denied, open '/root/.pm2/module_conf.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.Configuration.getAllSync (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Configuration.js:299:26)
    at Object.Configuration.getSync (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Configuration.js:270:30)
    at new API (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/API.js:117:44)
    at Object.<anonymous> (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/@pm2/agent/src/InteractorClient.js:58
          if (stats.uid === 0) {
                    ^

TypeError: Cannot read properties of undefined (reading 'uid')
    at /www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/@pm2/agent/src/InteractorClient.js:58:21
    at FSReqCallback.oncomplete (node:fs:198:21)

Node.js v17.3.0
[root@10-7-47-30 cq-picsearcher-bot-master]# npm start

> cq-picsearcher-bot@2.31.1 start
> pm2 start ecosystem.config.js

Error: EACCES: permission denied, mkdir '/root/.pm2/logs'
    at Object.mkdirSync (node:fs:1336:3)
    at mkdirpNativeSync (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
    at Function.mkdirpSync [as sync] (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/node_modules/mkdirp/index.js:21:7)
    at module.exports.Client.initFileStructure (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:133:25)
    at new module.exports (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:38:8)
    at new API (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
Error: EACCES: permission denied, mkdir '/root/.pm2/pids'
    at Object.mkdirSync (node:fs:1336:3)
    at mkdirpNativeSync (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
    at Function.mkdirpSync [as sync] (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/node_modules/mkdirp/index.js:21:7)
    at module.exports.Client.initFileStructure (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:141:25)
    at new module.exports (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:38:8)
    at new API (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
Error: EACCES: permission denied, open '/root/.pm2/module_conf.json'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2155:35)
    at module.exports.Client.initFileStructure (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:149:10)
    at new module.exports (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:38:8)
    at new API (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
Error: EACCES: permission denied, mkdir '/root/.pm2/modules'
    at Object.mkdirSync (node:fs:1336:3)
    at mkdirpNativeSync (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
    at Function.mkdirpSync [as sync] (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/node_modules/mkdirp/index.js:21:7)
    at module.exports.Client.initFileStructure (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:157:25)
    at new module.exports (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Client.js:38:8)
    at new API (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)

                        -------------

__/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
 _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
  _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
   _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
    _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
     _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
      _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
       _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
        _\///______________\///______________\///__\///////////////__


                          Runtime Edition

        PM2 is a Production Process Manager for Node.js applications
                     with a built-in Load Balancer.

                Start and Daemonize any application:
                $ pm2 start app.js

                Load Balance 4 instances of api.js:
                $ pm2 start api.js -i 4

                Monitor in production:
                $ pm2 monitor

                Make pm2 auto-boot at server restart:
                $ pm2 startup

                To go further checkout:
                http://pm2.io/


                        -------------

Error: EACCES: permission denied, open '/root/.pm2/module_conf.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.Configuration.getAllSync (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Configuration.js:299:26)
    at Object.Configuration.getSync (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/Configuration.js:270:30)
    at new API (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/API.js:117:44)
    at Object.<anonymous> (/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
/www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/@pm2/agent/src/InteractorClient.js:58
          if (stats.uid === 0) {
                    ^

TypeError: Cannot read properties of undefined (reading 'uid')
    at /www/wwwroot/qq机器人/cq-picsearcher-bot-master/node_modules/@pm2/agent/src/InteractorClient.js:58:21
    at FSReqCallback.oncomplete (node:fs:198:21)

Node.js v17.3.0
[root@10-7-47-30 cq-picsearcher-bot-master]#

**Comment by huankong233** [comment]
重新部署了项目倒是可以了

**Comment by huankong233** [comment]
奇怪了，我在win下可以启动的，到linux就告诉我没权限了

**Comment by huankong233** [comment]
咱们nodejs能接收到cqhttp的警告报错吗，最近机器人经常被风控，接收到了报错判断一下，然后跑个sh脚本让cqhttp重启一下，试试看能不能过风控

**Comment by Tsuk1ko** [comment]
> 咱们nodejs能接收到cqhttp的警告报错吗，最近机器人经常被风控，接收到了报错判断一下，然后跑个sh脚本让cqhttp重启一下，试试看能不能过风控

貌似不能

风控你只需要持续挂机几天就行了，不用那么麻烦

**Comment by Miuzarte** [comment]
> 咱们nodejs能接收到cqhttp的警告报错吗，最近机器人经常被风控，接收到了报错判断一下，然后跑个sh脚本让cqhttp重启一下，试试看能不能过风控

暂时禁用群聊一段时间，看看是不是群里有内鬼在举报，挂一段长时间还是风控就考虑重置device.json
