### ISSUE TITLE
--update-cqps失败

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#330]
![image](https://user-images.githubusercontent.com/66856838/175779536-1feb3947-87b3-4d90-a1df-ac40a3418e3d.png)
![image](https://user-images.githubusercontent.com/66856838/175779528-8b70f91d-7d04-4b92-926a-c248b4387a69.png)

**Comment by Miuzarte** [comment]
日志
```
六 6月 25  23:08:23
root@Tencent-HongKong:~$ tail ./cq-picsearcher-bot/logs/normal.log
2022/6/22 23:02:59 连接失败[/api]#20
2022/6/22 23:03:04 连接中[/event]#21
2022/6/22 23:03:04 连接失败[/event]#21
2022/6/22 23:03:04 连接中[/api]#21
2022/6/22 23:03:04 连接失败[/api]#21
2022/6/22 23:03:09 连接中[/event]#22
2022/6/22 23:03:09 连接成功[/event]#22
2022/6/22 23:03:09 连接中[/api]#22
2022/6/22 23:03:09 连接成功[/api]#22
2022/6/25 21:56:41 发现新版本：2.36.0
```
```
六 6月 25  23:08:38
root@Tencent-HongKong:~$ tail -20 ./cq-picsearcher-bot/logs/error.log
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
{
  "message": "Request failed with status code 404",
  "config": {}
}
2022/6/25 17:18:08 [error] nhentai
Error: Request failed with status code 503
    at createError (/root/cq-picsearcher-bot/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/root/cq-picsearcher-bot/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/root/cq-picsearcher-bot/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
{
  "message": "Request failed with status code 503",
  "config": {}
}
```

**Comment by Tsuk1ko** [comment]
安装依赖看看是否有报错

**Comment by Miuzarte** [comment]
> 安装依赖看看是否有报错

![image](https://user-images.githubusercontent.com/66856838/175801946-8f0ab835-01e9-40fe-b55d-8af98797e3dc.png)

**Comment by Tsuk1ko** [comment]
暂时看不出来原因

更新下最新代码，以后会把更新日志保存到 `logs/update/log`，如果还出现问题的话再看看

**Comment by Miuzarte** [comment]
![image](https://user-images.githubusercontent.com/66856838/177146987-9d5faa62-1624-4d4a-b519-7a9f55f5da76.png)
看来是git的锅，我重新拉取一份应该就能解决了

**Comment by Tsuk1ko** [comment]
可能是你之前的某些操作修改了文件

只要执行

```
git reset ea2dc7b --hard
```

就行了（硬重置到最新commit）

**Comment by Miuzarte** [comment]
> 可能是你之前的某些操作修改了文件
> 
> 只要执行
> 
> ```
> git reset ea2dc7b --hard
> ```
> 
> 就行了（硬重置到最新commit）

好的
