### ISSUE TITLE
哔哩推送增加'是否推送视频'的选项、增加订阅视频合集功能

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#335]
```diff
{
  // 群号
  "gid": 1234567890,
  // 是否推送动态
  "dynamic": false,
+  // 是否推送视频
+  "video": false,
  // 是否推送直播
  "live": false,
  // 推送动态是否@全体成员
  "dynamicAtAll": false,
+  // 推送视频是否@全体成员
+  "videoAtAll": false,
  // 推送直播是否@全体成员
  "liveAtAll": false
}
```
![image](https://user-images.githubusercontent.com/66856838/177154666-700c4456-bbbc-4eec-b4b9-0fbb20cfc7f7.png)
![image](https://user-images.githubusercontent.com/66856838/177154980-687d025a-135a-4d00-83a7-2f82a079ee7a.png)

**Comment by Miuzarte** [comment]
> 增加视频的选项意思是把视频从动态里分离出来单独做开关么

是的，有些UP订阅了只图他的视频（

**Comment by Tsuk1ko** [comment]
配置见 [wiki](https://github.com/Tsuk1ko/cq-picsearcher-bot/wiki/%E9%99%84%E5%8A%A0%E5%8A%9F%E8%83%BD#%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E6%8E%A8%E9%80%81)

不过我没法直接创建合集所以没得测试，日常使用的时候测测吧（

**Comment by Miuzarte** [comment]
> 配置见 [wiki](https://github.com/Tsuk1ko/cq-picsearcher-bot/wiki/%E9%99%84%E5%8A%A0%E5%8A%9F%E8%83%BD#%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E6%8E%A8%E9%80%81)
> 
> 不过我没法直接创建合集所以没得测试，日常使用的时候测测吧（

![image](https://user-images.githubusercontent.com/66856838/178386299-3e11925a-ca40-4c1a-87c7-e3bd58a0b9ef.png)
![image](https://user-images.githubusercontent.com/66856838/178386457-a8bbf855-5847-4e09-88e3-374798672d4e.png)
没起效
![image](https://user-images.githubusercontent.com/66856838/178386560-606e4232-cbc4-413e-9072-53992bfc1bc1.png)
不是风控

**Comment by Tsuk1ko** [comment]
有错误日志吗，error.log

**Comment by Miuzarte** [comment]
> 有错误日志吗，error.log

```
2022/7/11 22:07:03 [error] bilibili live data 11783021
TypeError: Cannot read property 'liveStatus' of null
    at getUserLiveData (/root/cq-picsearcher-bot/src/plugin/bilibili/live.js:41:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /root/cq-picsearcher-bot/src/plugin/bilibili/push.js:118:22
    at async Promise.all (index 0)
    at async checkLive (/root/cq-picsearcher-bot/src/plugin/bilibili/push.js:116:3)
    at async Promise.all (index 1)
    at async Timeout.checkPush [as _onTimeout] (/root/cq-picsearcher-bot/src/plugin/bilibili/push.js:64:5)
{
  "message": "Cannot read property 'liveStatus' of null"
}
2022/7/12 09:17:33 [error] bilibili live data 11783021
TypeError: Cannot read property 'liveStatus' of null
    at getUserLiveData (/root/cq-picsearcher-bot/src/plugin/bilibili/live.js:41:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /root/cq-picsearcher-bot/src/plugin/bilibili/push.js:118:22
    at async Promise.all (index 0)
    at async checkLive (/root/cq-picsearcher-bot/src/plugin/bilibili/push.js:116:3)
    at async Promise.all (index 1)
    at async Timeout.checkPush [as _onTimeout] (/root/cq-picsearcher-bot/src/plugin/bilibili/push.js:64:5)
{
  "message": "Cannot read property 'liveStatus' of null"
}

```
应该是没有

**Comment by Tsuk1ko** [comment]
怪，拿 mockAPI 试了下是没问题的
