### ISSUE TITLE
公招报错

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#384]
![image](https://user-images.githubusercontent.com/66856838/208892762-952a39a6-aa0d-4e13-b0fd-78cdcf7a3f7d.png)
![image](https://user-images.githubusercontent.com/66856838/208892949-fab86a76-60aa-471d-ac93-89111547c48b.png)
```
2022/12/21 19:15:14 [error] Akhr
2022/12/21 19:15:14 TypeError: Cannot read property 'createCanvas' of null
    at getImg (file:///C:/Users/Administrator/Desktop/cq-picsearcher-bot/src/plugin/akhr/akhr.draw.mjs:50:22)
    at Object.getResultImg (file:///C:/Users/Administrator/Desktop/cq-picsearcher-bot/src/plugin/akhr/index.mjs:170:10)
    at handleWords (file:///C:/Users/Administrator/Desktop/cq-picsearcher-bot/src/index.mjs:653:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022/12/21 19:15:28 Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'canvas' imported from C:\Users\Administrator\Desktop\cq-picsearcher-bot\libs\canvas\index.mjs
    at new NodeError (internal/errors.js:322:7)
    at packageResolve (internal/modules/esm/resolve.js:732:9)
    at moduleResolve (internal/modules/esm/resolve.js:773:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at Loader.import (internal/modules/esm/loader.js:177:28)
    at importModuleDynamically (internal/modules/esm/translators.js:114:35)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at loadCanvasModule (file:///C:/Users/Administrator/Desktop/cq-picsearcher-bot/libs/canvas/index.mjs:31:3) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by Tsuk1ko** [comment]
上次删的时候把 lib 里的 canvas 也删了吧，重新装一下

**Comment by Miuzarte** [comment]
> 上次删的时候把 lib 里的 canvas 也删了吧，重新装一下

![~45 5P)WT%531M3I$HH 70](https://user-images.githubusercontent.com/66856838/208895578-18732f06-e9f9-42cf-b696-f56637df39f2.png)
刚刚因为半天没反应就把v2.42的canvas复制过来，运行了试了下还是一样的错误
现在还在等npm i

**Comment by Tsuk1ko** [comment]
![image](https://user-images.githubusercontent.com/24877906/208896024-981fcddf-b83c-436f-a553-78c18c71815c.png)
你也可以试试直接用 `@napi-rs/canvas` 吧

**Comment by Miuzarte** [comment]
> @napi-rs/canvas



> ![image](https://user-images.githubusercontent.com/24877906/208896024-981fcddf-b83c-436f-a553-78c18c71815c.png) 你也可以试试直接用 `@napi-rs/canvas` 吧

解决了
