### ISSUE TITLE
涩图功能，Request failed with status code 400

### ISSUE THREAD

**Issue by Liangyu-G** [Tsuk1ko/cq-picsearcher-bot#402]
1. Bug 描述
   - 稳定复现
2. 截图、日志、配置（issue 内上传图片或文件可直接粘贴）
```
2023/3/25 13:36:45 [error]
2023/3/25 13:36:45 AxiosError: Request failed with status code 400
    at settle (file:///C:/%E5%90%84%E7%A7%8D%E6%96%87%E4%BB%B6%E5%A4%B9/%E6%90%9C%E5%9B%BEnew/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (file:///C:/%E5%90%84%E7%A7%8D%E6%96%87%E4%BB%B6%E5%A4%B9/%E6%90%9C%E5%9B%BEnew/node_modules/axios/lib/adapters/http.js:495:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023/3/25 13:36:45 {
  config: {
    method: 'post',
    url: 'https://api.lolicon.app/setu/v2',
    data: '{"size":["original","regular"],"proxy":null}'
  },
  response: { status: 400, statusText: 'Bad Request' }
```
3. 运行环境
   - Windows server 2016
   - node.js v18.14.0
   - cq-picsearcher-bot 3.7.1

**Comment by Liangyu-G** [comment]
补充一下，原来搜图也不行，草
`2023/3/25 13:52:16 [error] saucenao[0][request]
2023/3/25 13:52:16
2023/3/25 13:52:16 [error] ascii2d
2023/3/25 13:52:16 AxiosError: Request failed with status code 503
    at settle (file:///C:/%E5%90%84%E7%A7%8D%E6%96%87%E4%BB%B6%E5%A4%B9/%E6%90%9C%E5%9B%BEnew/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (file:///C:/%E5%90%84%E7%A7%8D%E6%96%87%E4%BB%B6%E5%A4%B9/%E6%90%9C%E5%9B%BEnew/node_modules/axios/lib/adapters/http.js:495:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023/3/25 13:52:16 {
  config: {
    method: 'get',
    url: 'https://ascii2d.net/search/url/https://gchat.qpic.cn/gchatpic_new/0/0-0-80A15C645492B1DB216F14F04C7BB2D9/0',
    data: undefined
  },
  response: { status: 503, statusText: 'Service Unavailable' }
}
2023/3/25 13:52:16 [error] getAntiShieldedCqImg64FromUrl
2023/3/25 13:52:16 AxiosError: Request failed with status code 400
    at settle (file:///C:/%E5%90%84%E7%A7%8D%E6%96%87%E4%BB%B6%E5%A4%B9/%E6%90%9C%E5%9B%BEnew/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (file:///C:/%E5%90%84%E7%A7%8D%E6%96%87%E4%BB%B6%E5%A4%B9/%E6%90%9C%E5%9B%BEnew/node_modules/axios/lib/adapters/http.js:495:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023/3/25 13:52:16 {
  config: {
    method: 'get',
    url: 'https://gchat.qpic.cn/gchatpic_new/0/0-0-80A15C645492B1DB216F14F04C7BB2D9/0',
    data: undefined
  },
  response: { status: 400, statusText: 'Bad Request' }`

**Comment by Liangyu-G** [comment]
代理已设置，正常使用
`    // 大部分请求所使用的代理，支持 http(s):// 和 socks://
    "proxy": "http://127.0.0.1:10809",`

**Comment by Tsuk1ko** [comment]
所以是好了？

**Comment by Liangyu-G** [comment]
不是不是，是代理正常设置的时候也不行

**Comment by Tsuk1ko** [comment]
感觉还是网或者代理有问题，目前搜图服务和色图服务都没问题

**Comment by Liangyu-G** [comment]
> 

代理连通性一直是正常的，当时测试了一下其他插件使用代理都可以正常使用，不过现在突然恢复了（），谢谢大佬的回复
