### ISSUE TITLE
公招数据库是不是寄了

### ISSUE THREAD

**Issue by Miuzarte** [Tsuk1ko/cq-picsearcher-bot#408]
```log
4/7/2023, 10:18:36 AM 方舟公招数据更新
4/7/2023, 10:18:36 AM AxiosError: Request failed with status code 404
    at settle (file:///home/rurudo/cq-picsearcher-bot/node_modules/axios/lib/core/settle.js:19:12)
    at BrotliDecompress.handleStreamEnd (file:///home/rurudo/cq-picsearcher-bot/node_modules/axios/lib/adapters/http.js:495:11)
    at BrotliDecompress.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
4/7/2023, 10:18:36 AM {
  config: {
    method: 'get',
    url: 'https://fastly.jsdelivr.net/gh/arkntools/arknights-toolbox@master/src/locales/cn/character.json',
    data: undefined
  },
  response: { status: 404, statusText: 'Not Found' }
}
```
![image](https://user-images.githubusercontent.com/66856838/230527635-ceefe3c9-4297-43d5-863b-95d5ce5e4262.png)
![image](https://user-images.githubusercontent.com/66856838/230527576-ca534246-0c7b-47f8-b9cd-9ad2ba520068.png)

**Comment by Tsuk1ko** [comment]
我方舟工具箱改造了下把数据迁到别的仓库了，这里忘改了🥲
